@host = http://fauques.freeboxos.fr:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Njg3ZDZiOC0zNjJiLTQ1MTItYjNhNy0zNGU5ODRlYjhkZDkiLCJ1c2VybmFtZSI6IkxvIiwiaWF0IjoxNjgxMzMzOTM4LCJleHAiOjE3MTI4OTE1Mzh9.MQ3B4egyOsPpRif5zqGx_IXJ4FyjqozU-LQX6AHCfio

POST {{host}}/login
Content-Type: application/json

{
  "username": "test21",
  "password": "test"
}


###
GET {{host}}/matches
Authorization: Bearer {{token}}

###
POST {{host}}/matches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI5NmZlZmFiMS1lYTQ3LTQwOTAtYjEwMi0xNTliMjczMDUwMDkiLCJ1c2VybmFtZSI6InRlc3QyMSIsImlhdCI6MTY4MTU4MjI5MCwiZXhwIjoxNzEzMTM5ODkwfQ.B1btyGUa98zxNF6Cbb7hGOwPlghF2ngxUFHbuXHyDa8
###
POST {{host}}/matches/643d8e211e1b9407b262bc8f/turns/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI5NmZlZmFiMS1lYTQ3LTQwOTAtYjEwMi0xNTliMjczMDUwMDkiLCJ1c2VybmFtZSI6InRlc3QyMSIsImlhdCI6MTY4MTU4MjI5MCwiZXhwIjoxNzEzMTM5ODkwfQ.B1btyGUa98zxNF6Cbb7hGOwPlghF2ngxUFHbuXHyDa8
Content-Type: application/json

{
 "move": "rock" 
}
###
POST {{host}}/matches/64382c5c1e1b9407b260f34f/turns/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
 "move": "scissors" 
}

###

GET {{host}}/matches/643521a71e1b9407b260ea3b
Authorization: Bearer {{token}}

###
